name: "Lint"

on:
  push:
    branch:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
          
